apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: k8s-oidc-authenticator
    chartname: {{ .Chart.Name }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        chartname: {{ .Chart.Name }}
        app: k8s-oidc-authenticator
    spec:
      containers:
      - name: k8s-oidc-authenticator
        image: {{ .Values.deployment.image }}
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
        env:
          - name: CALLBACK_URL
            value: https://{{ .Values.ingress.hostname }}/callback
          - name: CLIENT_ID
            value: {{ .Values.oidc.client_id }}
          - name: CLIENT_SECRET
            value: {{ .Values.oidc.client_secret }}
          - name: ALLOWED_DOMAIN
            value: {{ .Values.oidc.allowed_domain }}
          - name: ALLOWED_EMAIL_ADDRESSES
            value: {{ template "allowed_email_addresses" . }}
{{- if .Values.cluster_ca_data }}
          - name: CA_DATA
            value: {{ .Values.cluster_ca_data }}
{{- end }}
{{- if .Values.cluster_name }}
          - name: CLUSTER_NAME
            value: {{ .Values.cluster_name }}
{{- end }}
        ports:
          - containerPort: 8080
            protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
      restartPolicy: Always
